site_name: Comics Reaing Order
theme: 
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:

      # Palette toggle for dark mode
    - scheme: slate
      primary: black # website default should already be in dark mode so this color should be set to a black color
      accent: deep orange # this changes the color of links when you hover over them
      toggle:
        icon: material/weather-night
        name: Switch to light mode

      # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode 








#look at 17:30 in https://www.youtube.com/watch?v=NY7DHvo1XVM to see how to use custom navigation
