site_name: Comics Reaing Order
nav:
  - Home: index.md
  - About: about.md
theme: 
  name: material
  language: en
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
   - typeset
   - search

  palette:
     # Palette toggle for dark mode
    - scheme: slate
      primary: black # website default should already be in dark mode so this color should be set to a black color
      accent: deep orange # this changes the color of links when you hover over them
      toggle:
        icon: material/weather-night
        name: Switch to light mode

      # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode 

markdown_extensions:
   - admonition #these are info boxes that are colored, with name, and icon, that can be expanded/collapsable
   - pymdownx.details
   - pymdownx.superfences
   - toc:
      permalink: true





#look at 17:30 in https://www.youtube.com/watch?v=NY7DHvo1XVM to see how to use custom navigation
 # cloudflare pages to host the website just like pvme and kenharris.io 20 minute mark in previous link